apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fiap-todo-prod

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: production

images:
- name: fiap-todo-api
  newName: 197890406314.dkr.ecr.us-east-1.amazonaws.com/fiap-todo-api
  newTag: 610dda9c8c4e5c097ae0a8b4df3fecb5a5470ffe
